// const nodemailer = require('nodemailer')

// // Create reusable transporter
// const createTransporter = () => {
//   return nodemailer.createTransport({
//     service: process.env.EMAIL_SERVICE || 'gmail',
//     auth: {
//       user: process.env.EMAIL_USER,
//       pass: process.env.EMAIL_PASSWORD
//     }
//   })
// }

// // Send contact email
// const sendContactEmail = async (req, res) => {
//   try {
//     const { name, email, phone, message } = req.body

//     // Validation
//     if (!name || !email || !phone || !message) {
//       return res.status(400).json({
//         success: false,
//         message: 'All fields are required'
//       })
//     }

//     // Email validation
//     const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
//     if (!emailRegex.test(email)) {
//       return res.status(400).json({
//         success: false,
//         message: 'Invalid email format'
//       })
//     }

//     const transporter = createTransporter()

//     // 📩 Admin Email Template
//     const adminMailOptions = {
//       from: process.env.EMAIL_USER,
//       to: process.env.ADMIN_EMAIL || 'contact@Globuzindia.in',
//       subject: `📥 New Contact Form Submission - ${name}`,
//       html: `
//       <div style="background-color:#f6f8fb; padding:40px 0; font-family:'Segoe UI', Arial, sans-serif;">
//         <div style="max-width:650px; margin:auto; background-color:#ffffff; border-radius:10px; overflow:hidden; box-shadow:0 4px 20px rgba(0,0,0,0.05);">
//           <div style="background-color:#0056D2; padding:20px 30px;">
//             <h1 style="color:#ffffff; margin:0; font-size:22px;">Globuz India</h1>
//             <p style="color:#cfe2ff; margin:0; font-size:14px;">New Contact Submission Received</p>
//           </div>
//           <div style="padding:30px;">
//             <h2 style="color:#333333; font-size:20px; margin-bottom:20px;">Contact Details</h2>
//             <table style="width:100%; border-collapse:collapse;">
//               <tr><td style="padding:8px 0; width:150px; color:#666;">👤 <b>Name:</b></td><td>${name}</td></tr>
//               <tr><td style="padding:8px 0; color:#666;">📧 <b>Email:</b></td><td>${email}</td></tr>
//               <tr><td style="padding:8px 0; color:#666;">📞 <b>Phone:</b></td><td>${phone}</td></tr>
//             </table>
//             <div style="margin-top:25px;">
//               <h3 style="color:#333; font-size:18px;">💬 Message:</h3>
//               <div style="background-color:#f3f5f9; padding:15px; border-radius:8px; color:#333; line-height:1.6;">
//                 ${message}
//               </div>
//             </div>
//           </div>
//           <div style="background-color:#f1f4f8; padding:15px 30px; text-align:center; font-size:12px; color:#888;">
//             <p style="margin:0;">This message was automatically generated by the Globuz India contact form.</p>
//           </div>
//         </div>
//       </div>
//       `
//     }

//     // 📧 User Confirmation Template
//     const userMailOptions = {
//       from: process.env.EMAIL_USER,
//       to: email,
//       subject: '✅ We’ve received your message — Globuz India',
//       html: `
//       <div style="background-color:#f6f8fb; padding:40px 0; font-family:'Segoe UI', Arial, sans-serif;">
//         <div style="max-width:650px; margin:auto; background-color:#ffffff; border-radius:10px; overflow:hidden; box-shadow:0 4px 20px rgba(0,0,0,0.05);">
//           <div style="background-color:#0056D2; padding:20px 30px; text-align:center;">
//             <h1 style="color:#ffffff; margin:0; font-size:22px;">Globuz India</h1>
//             <p style="color:#cfe2ff; margin:0; font-size:14px;">Thank You for Contacting Us</p>
//           </div>
//           <div style="padding:30px;">
//             <p style="font-size:16px; color:#333;">Dear <b>${name}</b>,</p>
//             <p style="color:#555; line-height:1.6;">
//               We’ve received your message and our team will get in touch with you shortly.  
//               Here’s a copy of your submission for your reference:
//             </p>
//             <div style="background-color:#f3f5f9; padding:15px; border-radius:8px; margin:20px 0;">
//               <h3 style="color:#333; font-size:16px; margin-top:0;">Your Message:</h3>
//               <p style="color:#333; line-height:1.6; margin:0;">${message}</p>
//             </div>
//             <p style="color:#555;">Warm regards,</p>
//             <p style="color:#0056D2; font-weight:bold;">Globuz India Team</p>
//           </div>
//          <div style="background-color:#f1f4f8; padding:20px; text-align:center; font-size:12px; color:#888;">
//           <p style="margin:0;">Navkar Bhavsar & Co. | Ahmedabad, Gujarat - 380054</p>
//           <p style="margin:5px 0;">📍 Privillion East Wing, 2nd Floor, Behind Iskon Temple, SG Highway</p>
//           <p style="margin:5px 0;">📞 +91 95868 19690 | +91 89806 96886</p>
//           <p style="margin:0;">📧 contact@Globuzindia.in</p>
//         </div>

//         </div>
//       </div>
//       `
//     }

//     // Send both emails
//     await transporter.sendMail(adminMailOptions)
//     await transporter.sendMail(userMailOptions)

//     res.status(200).json({
//       success: true,
//       message:
//         'Your message has been sent successfully! We’ll contact you soon.'
//     })
//   } catch (error) {
//     console.error('Error sending email:', error)
//     res.status(500).json({
//       success: false,
//       message: 'Failed to send message. Please try again later.',
//       error: process.env.NODE_ENV === 'development' ? error.message : undefined
//     })
//   }
// }

// module.exports = { sendContactEmail }


const sendEmail = require("../utils/googleTransporter");

const sendContactEmail = async (req, res) => {
  try {
    const { name, email, phone, message } = req.body;

    if (!name || !email || !phone || !message) {
      return res.status(400).json({ success: false, message: "All fields are required" });
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return res.status(400).json({ success: false, message: "Invalid email format" });
    }

    // Admin Email
    const adminHtml = `
      <div style="background:#f6f8fb; padding:20px; font-family:sans-serif;">
        <h2>New Contact Submission</h2>
        <p><b>Name:</b> ${name}</p>
        <p><b>Email:</b> ${email}</p>
        <p><b>Phone:</b> ${phone}</p>
        <p><b>Message:</b> ${message}</p>
      </div>
    `;

    // User Confirmation Email
    const userHtml = `
      <div style="background:#f6f8fb; padding:20px; font-family:sans-serif;">
        <h2>Thank You, ${name}</h2>
        <p>We’ve received your message and our team will contact you soon.</p>
        <p><b>Your Message:</b> ${message}</p>
      </div>
    `;

    await sendEmail(process.env.ADMIN_EMAIL, `📥 New Contact Form Submission - ${name}`, adminHtml);
    await sendEmail(email, "✅ We’ve received your message — Globuz India", userHtml);

    res.status(200).json({ success: true, message: "Your message has been sent successfully!" });
  } catch (error) {
    console.error("Error sending email:", error);
    res.status(500).json({ success: false, message: "Failed to send message.", error: error.message });
  }
};

module.exports = { sendContactEmail };

